### ISSUE TITLE
slug changes

### ISSUE THREAD

**Issue by iamtraction** [gocobalt/cobalt-js#1]
- [x] Add get app by slug function https://github.com/gocobalt/bkout_one_workflow_backend/issues/404
- [x] Migrate all functions to use app slug instead of app ID https://github.com/gocobalt/bkout_one_workflow_backend/issues/423
- [x] Combine all auth functions into a single function https://github.com/gocobalt/bkout_one_workflow_backend/issues/423
- [x] Remove unused config functions
